# Generated by Django 4.1.6 on 2023-06-15 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_season', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_series', models.IntegerField()),
                ('preview', models.ImageField(upload_to='preview')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.season')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='image')),
                ('cost', models.IntegerField()),
                ('raiting', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('description', models.TextField(max_length=160)),
                ('country', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('date_of_issue', models.CharField(max_length=6)),
                ('trailer', models.FileField(upload_to='trailer')),
                ('category', models.ManyToManyField(to='catalog.category')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.serial'),
        ),
    ]
