# Generated by Django 4.1.6 on 2023-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
